# fly.toml app configuration file generated for silent-snowflake-5507 on 2023-05-26T11:47:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "silent-snowflake-5507"
primary_region = "lax"

[build]
  image = "macross2/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dh1ncuyui"
  CloudinarySettings__ApiKey="878135373958519"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
